name: Deploy Firebase Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - "functions/**"
      - "firebase.json"
      - ".github/workflows/deploy-functions.yml"
      - ".firebaserc"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug (list root + show firebase.json)
        run: |
          echo "PWD:"
          pwd
          echo "ROOT FILES:"
          ls -la
          echo "FIND firebase.json:"
          find . -maxdepth 3 -name "firebase.json" -print
          echo "CAT firebase.json:"
          cat firebase.json

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Write service account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-sa.json

      - name: Install functions deps
        run: |
          cd functions
          npm install

        - name: Deploy Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-sa.json
        run: |
          firebase deploy --only functions --project financial-dashboard-a2b16
