name: Deploy Firebase Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - "functions/**"
      - "firebase.json"
      - ".github/workflows/deploy-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Debug (list root + show firebase.json)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name "firebase.json" -print
          cat firebase.json

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # Autentica no Google Cloud usando o JSON da Service Account
      - id: gcp-auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install functions deps
        run: |
          cd functions
          npm install

      - name: Deploy Functions
        run: |
          firebase deploy --only functions --project financial-dashboard-a2b16
